### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by JonoB** [jimdoescode/CodeIgniter-GitHub-Updater#1]
OK, this looks freakin awesome. Two questions:
1. Does the ignore_files array also work on entire directories?
2. How does the updater know where to put the new files? Does it just assume that its going to work in the current directory? What happens if you store your CI files above the webroot?

**Comment by jimdoescode** [comment]
1. No the ignore list is on a file by file basis, but that is a good idea I will look into adding it.
2. When the updater compares the local commit to the github commit it gets back a list of changed files. Included in that list is a relative path to each file. The library has to assume that the relative path it get's back from github is based in the webroot. So basically everything has to be below the web root right now.

**Comment by jimdoescode** [comment]
I altered the way ignoring works. You should be able to use a directory as well as a file now. You also don't have to be so specific about what you want ignored. For instance you can say 'config.php' and any file with that name will be ignored.

I am not really sure what to do about applications running outside the webroot. If you come up with a solution feel free to fork this repo and implement it. I was thinking along the lines of a config option that allows you to set a full path to your actual root and default to the webroot if that option isn't present.
