### ISSUE TITLE
Private Repo's

### ISSUE THREAD

**Issue by sdrib** [jimdoescode/CodeIgniter-GitHub-Updater#2]
As mentioned in your blog post, this does not work for private repo's
I'm making changes to make this work though. When and if it's done I'll send a pull requests:).

**Comment by jimdoescode** [comment]
Looking forward to it

**Comment by sdrib** [comment]
I have been tinkering a bit with this, there are different ways to do this with the current API though.
Not sure which ones would be the best.

http://developer.github.com/v3/oauth/

**Comment by jimdoescode** [comment]
It doesn't really make sense to use the web flow because this would only be for a single user. Also the library shouldn't expose any url routes. I would recommend using this method http://developer.github.com/v3/oauth/#create-a-new-authorization

**Comment by sdrib** [comment]
Hmm that's what I was thinking too.
You do have to register a new application in your github account, but it works fine.

Thanks for the feedback, I'll continue with this

**Comment by sdrib** [comment]
Finally got some time to focus on this. I'm almost there!

Stumbled onto a few issues though:
- Downloading the zip file from a private repo seems not possible without curl.
- `curl_exec()` is giving me too many permission problems I'm using `ZipArchive` instead. It's a native class.
  The Zip extension needs to be active though.

**Comment by stringariSM** [comment]
Hello, how are you?

Have you made any changes to private repositories?

**Comment by sdrib** [comment]
I had to drop this when I switched jobs unfortunately @stringariSM
